package com.example.sitconnect2.features.attendance.domain.model

import java.util.Date

enum class AttendanceType {
    LAB,
    TUTORIAL,
    LECTURE
}

enum class AttendanceStatus {
    PRESENT,
    ABSENT,
    LATE,
    EXCUSED
}

data class AttendanceSession(
    val id: String = "",
    val scheduleId: String = "", // Link to schedule document
    val moduleCode: String = "",
    val moduleName: String = "",
    val sessionType: AttendanceType = AttendanceType.LAB,
    val dayOfWeek: Int = 1, // 1 = Monday, 7 = Sunday
    val sessionDate: Date = Date(),
    val startTime: String = "",
    val endTime: String = "",
    val venue: String = "",
    val attendanceCode: String = "", // Code generated by lecturer for verification
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val radiusMeters: Int = 100,
    val lecturerId: String = "",
    val lecturerName: String = ""
)

data class AttendanceRecord(
    val id: String = "",
    val sessionId: String = "",
    val scheduleId: String = "", // Link to schedule for easy querying
    val studentId: String = "",
    val weekLabel: String = "", // e.g. "2026-W12" — identifies which week the attendance is for
    val status: AttendanceStatus = AttendanceStatus.ABSENT,
    val markedAt: Date? = null,
    val markedVia: String = "", // "CODE+GPS" or "GPS" or "MANUAL"
    val latitude: Double? = null,
    val longitude: Double? = null
)

data class StudentAttendanceSummary(
    val moduleCode: String = "",
    val moduleName: String = "",
    val totalSessions: Int = 0,
    val attended: Int = 0,
    val absent: Int = 0,
    val late: Int = 0,
    val excused: Int = 0,
    val attendancePercentage: Float = 0f
)

